--- 
title: "Lecture Notes for Biology of Wildlife Populations"
author: "Andrew Tyre"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: atyre2/NRES450_book
description: "These are the lecture notes for NRES 450 Biology of Wildlife populations at the University of Nebraska."
---

# Prerequisites

I assume you have installed R and RStudio to run examples shown in each chapter.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

I originally set out to write this book because no existing population dynamics texts had the right mix of topics, or didn't address management related questions, or were far too advanced for an undergraduate audience. 
My educational objectives for the course, and for the curriculum in which it is embedded, are as follows.

1. Estimate the abundance of a species witin a specific geographical area, and critically evaluate the utility of abundance estimates.
2. Evaluate the impacts of habitat change on future population abundance. 
3. Assess how changes in harvest regulations will affect population abundance.
4. Assess the effect of competitors, predators and other species on a focal species.
5. Predict the consequences of alternative management actions in a Structured Decision Making framework using simple population models.
6. Identify the management decision(s) and the decision maker(s) relevant to a wildlife issue. 
7. Articulate the objectives of stakeholders along a means/ends continuum.
8. Enumerate available management actions and assemble alternative strategies.
9. Make tradeoffs between competing objectives to select a preferred management strategy in an SDM framework.

I think objectives 2, 3 and 4 could be subsumed into objective 5, but I've left them broken out for the moment. Objectives 6, 7, 8 and 9 relate directly to using the PrOACT model of Structured Decision Making. Objective 7 is the same as Larkin's proximate/ultimate distinction, I think. NRES 311 currently addresses completely or at least introduces 1-3 and 6-9; I'm not sure about 4. 
